import {
  BrowserModule,
  BrowserTransferStateModule,
} from "@angular/platform-browser";
import { NgModule } from "@angular/core";
import { AppRoutingModule } from '@src/app/app-routing.module';
import { ReactiveFormsModule, FormsModule } from "@angular/forms";
import { HttpClientModule, HTTP_INTERCEPTORS } from "@angular/common/http";

// Third party modules
import { NgbModule } from "@ng-bootstrap/ng-bootstrap";

import { LoadingBarRouterModule } from "@ngx-loading-bar/router";
import { LoadingBarHttpClientModule } from "@ngx-loading-bar/http-client";

import { JwtInterceptor, ErrorInterceptor } from '@src/app/_helpers';

// Components
import { AppComponent } from '@src/app/app.component';
import { AccountModule } from '@src/app/account/account.module';
import { RouletteModule } from '@src/app/roulette/roulette.module';

import { HomeComponent } from '@src/app/home/home.component';
import { AboutComponent } from '@src/app/home/misc/about/about.component';
import { DatenschutzComponent } from '@src/app/home/misc/datenschutz/datenschutz.component';
import { HelpSupportComponent } from '@src/app/home/misc/help-support/help-support.component';
import { FeedbackComponent } from '@src/app/home/misc/feedback/feedback.component';
import { ImpressumComponent } from '@src/app/home/misc/impressum/impressum.component';
import { ParentsComponent } from '@src/app/home/misc/parents/parents.component';
import { PrivacyComponent } from '@src/app/home/misc/privacy/privacy.component';
import { SchoolsComponent } from '@src/app/home/misc/schools/schools.component';
import { StudentsComponent } from '@src/app/home/misc/students/students.component';
import { TutorsComponent } from '@src/app/home/misc/tutors/tutors.component';
import { TermsConditionsComponent } from '@src/app/home/misc/terms-conditions/terms-conditions.component';
import { FooterComponent } from '@src/app/home/misc/footer/footer.component';
import { NavbarComponent } from '@src/app/home/misc/navbar/navbar.component';
import { PageNotFoundComponent } from '@src/app/home/misc/page-not-found/page-not-found.component';

import {
  DatabaseService,
  AuthenticationService,
  ToastService,
  RouletteService,
  BannerService,
} from '@src/app/_services';

import { MiscComponentsModule } from '@src/app/_misc_components/misc-components.module';
import { MoreInformationComponent } from '@src/app/home/more-information/more-information.component';
import { BannerComponent } from '@src/app/home/misc/banner/banner.component';
import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { ScrollSpyDirective } from '@src/app/_helpers/scroll-spy.directive';
import { PartnersComponent } from '@src/app/home/more-information/partners/partners.component';
import { FeaturesComponent } from '@src/app/home/more-information/features/features.component';
import { VideoComponent } from '@src/app/home/more-information/video/video.component';
import { MissionComponent } from '@src/app/home/more-information/mission/mission.component';
import { NumbersComponent } from '@src/app/home/more-information/numbers/numbers.component';
import { TeamComponent } from '@src/app/home/more-information/team/team.component';
import { JoinTheCommunityComponent } from '@src/app/home/more-information/join-the-community/join-the-community.component';
import { SocialIconsComponent } from '@src/app/home/misc/social-icons/social-icons.component';
import { PressComponent } from '@src/app/home/misc/press/press.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    MoreInformationComponent,
    AboutComponent,
    DatenschutzComponent,
    FeedbackComponent,
    HelpSupportComponent,
    ImpressumComponent,
    ParentsComponent,
    PrivacyComponent,
    SchoolsComponent,
    StudentsComponent,
    TutorsComponent,
    TermsConditionsComponent,
    FooterComponent,
    NavbarComponent,
    PageNotFoundComponent,
    BannerComponent,
    DashboardComponent,
    ScrollSpyDirective,
    PartnersComponent,
    FeaturesComponent,
    VideoComponent,
    MissionComponent,
    NumbersComponent,
    TeamComponent,
    JoinTheCommunityComponent,
    SocialIconsComponent,
    PressComponent,
    AutoGeneratedComponent,
  ],
  imports: [
    NgbModule,
    BrowserModule.withServerTransition({ appId: "serverApp" }),
    BrowserTransferStateModule,
    HttpClientModule,
    // Loading bar
    LoadingBarHttpClientModule,
    LoadingBarRouterModule,
    // Stuff for reactive / template driven forms
    ReactiveFormsModule,
    FormsModule,
    // modules (arbitrary order)
    AccountModule,
    RouletteModule,
    MiscComponentsModule,
    // AppRoutingComponent needs to be the last routing module
    AppRoutingModule,
  ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: JwtInterceptor, multi: true },
    { provide: HTTP_INTERCEPTORS, useClass: ErrorInterceptor, multi: true },
    AuthenticationService,
    DatabaseService,
    RouletteService,
    ToastService,
    BannerService,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
